### ISSUE TITLE
possible broken dep in ros-eigenpy-devel

### ISSUE THREAD

**Issue by ntorresalberto** [morxa/rosfed#1]
Is this the correct place to post these issues or should I go to pagure?

```
$ sudo dnf install ros-eigenpy-devel
Error: 
 Problem: conflicting requests
  - nothing provides ros-melodic-catkin-devel needed by ros-eigenpy-devel-melodic.2.3.1-1.fc32.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by morxa** [comment]
Yeah that looks broken. Just to be sure, this is on Fedora 32?

**Comment by ntorresalberto** [comment]
> Yeah that looks broken. Just to be sure, this is on Fedora 32?

Yes

**Comment by morxa** [comment]
Can you update to Fedora 33 or Fedora 34 and try again? Fedora 32 is EOL.

**Comment by ntorresalberto** [comment]
I upgraded:

```
# dnf install ros-eigenpy-devel
No match for argument: ros-eigenpy-devel
```

**Comment by morxa** [comment]
The problem was that no other package depends on eigenpy anymore, so it was not pulled in and rebuilt.

I've now rebuilt the package for F33 and F34, can you try again?

**Comment by ntorresalberto** [comment]
It worked in F33.
Closing the issue, thanks.
