### ISSUE TITLE
Issues on Fedora 37

### ISSUE THREAD

**Issue by npv12** [morxa/rosfed#11]
I am aware fedora 37 isn't officially out yet. But posting them as a headsup/to make the issue known.

ros-desktop doesn't install with the following error

```
Error: 
 Problem: package ros-desktop-noetic.1.5.0-3.fc36.noarch requires ros-noetic-common_tutorials, but none of the providers can be installed
  - package ros-common_tutorials-noetic.0.2.0-3.fc36.noarch requires ros-noetic-turtle_actionlib, but none of the providers can be installed
  - conflicting requests
  - nothing provides libboost_thread.so.1.76.0()(64bit) needed by ros-turtle_actionlib-noetic.0.2.0-3.fc36.x86_64
```

**Comment by xhertan** [comment]
Same problem here, ros-desktop is not installing on Fedora 37 from this repo. Any solution?

**Comment by Bearzeng** [comment]
Same problem on Fedora 38.

**Comment by kylevernyi** [comment]
Same problem Fedora 38. Any solutions?

**Comment by morxa** [comment]
My apologies for not following up on this, this repository is no longer maintained, see https://github.com/morxa/rosfed?tab=readme-ov-file#deprecation-notice.
