### ISSUE TITLE
Update the distro default for rosfed.py

### ISSUE THREAD

**Issue by martinezjavier** [morxa/rosfed#5]
The current `distro` default in `rosfed.py` is kinetic, but that is already EOL according to the [ROS wiki](http://wiki.ros.org/Distributions).

Should the default be updated to melodic or noetic ?

**Comment by morxa** [comment]
Yes, that should be updated! I'd opt for noetic.

**Comment by martinezjavier** [comment]
@morxa Ok, I've added another commit to PR #4 then.
