### ISSUE TITLE
geographic_msgs package

### ISSUE THREAD

**Issue by alexander-kapustin-qs** [morxa/rosfed#8]
Hi.
Thank you for this fedora ros copr!
What about geographic_msgs ros package?

**Comment by alexander-kapustin-qs** [comment]
I try to install it manually:

geograpic_msgs depends on uuid_msgs.

```sh
./rosfed.py uuid_msgs -c "Add uuid msgs"
spectool -g ros-uuid_msgs.spec -C ~/rpmbuild/SOURCES
rpmbuild -bs ros-uuid_msgs.spec
```
Then i try to install rpm:
```sh
rpm -ihv ~/rpmbuild/SRPMS/ros-uuid_msgs-noetic.1.0.6-1.fc35.src.rpm
```
Nothing happens- it looks like there is no installation section in rpm.

Sorry, i am not familiar with fedora rpm system very well..

**Comment by morxa** [comment]
Thanks for pointing this out! It seems like this was not pulled in as a dependency of any of the meta packages, which is why it wasn't built. I've now built the package and all its dependencies.
